= git-mr-to(1)
:man source: git mr-to 1.1.0
:man manual: git mr-to
:uri-flow: \https://scottchacon.com/2011/08/31/github-flow.html

== NAME

git-mr-to - Open Web browser at URL to create new merge request

== SYNOPSIS

*git mr-to* [_remote_ [_destination_ [_source_]]]

== DESCRIPTION

*git mr-to* opens a Web browser at the URL for creating a new _merge request_.
It is optimized for workflows where topic branches are merged directly to the
_master_ branch, such as the popular _GitHub
Flow_{empty}footnote:github-flow[{uri-flow}].

*git mr-to* has varying degrees of support for, in alphabetical order, the
following repository hosting services:

* Azure DevOps
* Bitbucket
* GitHub
* GitLab

See *<<_provider_support>>* for details.

== OPTIONS

_remote_::

    The remote against whose project URL to create the merge request. If only a
    single remote is configured in the repository, all arguments can be omitted
    to create a merge request from the _current branch_ to the _master_ branch
    of the configured remote.


_destination_::

    The branch in _remote_ to merge into. If omitted it defaults to _master_.


_source_::

    The branch to merge into _destination_. If omitted it defaults to the
    _current branch_.

== PROVIDER SUPPORT

Functionality depends on the repository hosting service provider. Here are all
the supported providers and their limitations:

_Azure DevOps_::

    Limited to intra-project merge requests. Inter-project merge requests are
    not supported because the URL format for this scenario uses internal
    project IDs instead of project names.

_Bitbucket_::

    Limited to intra-project merge requests. Inter-project merge requests are
    not supported because no working URL format for this scenario has been
    found.

_GitHub_::

    Full intra-project and inter-project merge request support.

_GitLab_::

    Limited to intra-project merge requests. Inter-project merge requests are
    not supported because the URL format for this scenario uses internal
    numerical project IDs instead of project names.

Inter-project support requires the downstream remote -- i.e., your fork -- to
be named _origin_. If a repository has multiple configured remotes, none of
which are named _origin_, *git mr-to* will not be able to infer the
upstream/downstream relationship. In that case it will issue a warning but
proceed, allowing the user to configure the merge request manually.

== ENVIRONMENT VARIABLES

The program's behavior can be altered with an environment variable:

*GIT_MR_TO_BROWSER*::

    When the environment variable *GIT_MR_TO_BROWSER* is set, it names a
    command with which to open the merge request Web page instead of the
    default command of *git-web\--browse*(1).
+
*git-web\--browse*(1) tries to either open a new tab in an existing browser or
start a new browser. Refer to its manual page for instructions on how to
configure its default browser.

== EXAMPLES

Create a merge request from the _current branch_ towards _master_ of the sole
configured remote; error in case of no or multiple remotes:

----
$ git mr-to
----

Create a merge request from the local _frobnicate-discombobulator_ branch
towards the _staging_ branch of the remote named _upstream_:

----
$ git mr-to upstream staging frobnicate-discombobulator
----


Open the merge request in *lynx*(1) (probably not recommended...) by overriding
*git-web--browse*(1)'s default browser with the _--browser_ option, by
overriding *git mr-to*'s default browser command via *GIT_MR_TO_BROWSER* (yes,
this is redundant):

----
$ GIT_MR_TO_BROWSER="git web--browse --browser=lynx" git mr-to
----

== AUTHOR

link:mailto:commonquail@gmail.com[Mikkel Kjeldsen]

== REPORTING BUGS

Report bugs and feature requests on the main project development page at
https://gitlab.com/mkjeldsen/git-mr-to/

== COPYRIGHT

Copyright (C) 2018-2021 Mikkel Kjeldsen

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License version 2 as published by the Free
Software Foundation.
